/*
   * Library to handle threads
   * THis library allows programs to easily create threads using the pthreads library. Your library shall create threads,
   * kill threads, maintain the stae of the threads and use signals to allow the state of the threads generated by the 
   * library to be displayed to the user. THe nubmer of threads supported by this library can be limited to 50 (dynamic allocation not required)
   *
   *
   * @author brandon tarney
   * @date  5/10/2017
   */
#ifndef THREAD_MGR_H
#define THREAD_MGR_H

typedef int ThreadHandles;
typedef void *Funcptrs(void*);

ThreadHandles th_execute(Funcptrs);

int th_wait(ThreadHandles);

int th_wait_all(void);

int th_kill(ThreadHandles);

int th_kill_all(void);

int th_exit(void);

extern const char* enumString[3];

extern char *logfile;

/*
   * LOG_EVENT
   * <p>Take the argument information, format it into a time-tagged line of text, and append it to the current log file.<p>
   * <p>No text msgs should appear garbled or lost in the log_file, regardless of # of proc. running & logging.<p>
   *
   * @param     I       Log leve
   * @param     fmt     character pointer to a string containing a format specfication for hte log messages. This format string is similar in funciton to the format string in the prinf() familiy of standard output routines
   * @param     ...    parameters of varying types and count (argument list) use vsprintf() function which takes a variable of type va_list as its last argument 
   *
   * @return    int    OK (0) upon successful return and ERROR (-1) otherwise
   */
int log_event(Levels I, const char *fmt, ...);

/*
   * SET_LOGFILE
   * <p>Allows the user to change th file used for the logging of messages for a particular process.<p>
   * <p>Not required to call this fcn before log_event()<p>
   * <p>When called, file is opened (or created), if success prev. logfile closed, new file used for log_event()<p>
   *
   * @param     logfile_name    name of file to open or create
   *
   * @return    int    OK (0) upon successful return and ERROR (-1) otherwise
   */
int set_logfile(const char* logfile_name);

/*
   * CLOSE_LOGFILE
   * <p>Called whenever a logfile is to be closed. At a minimum this function should close the FD associated w/ open logfile.<p>
   *
   * @param
   * @return
   *
   */
void close_logfile(void);

#endif
